#!/usr/bin/env python3
"""
Inject baseline accessibility scaffolding into every hand-written page (idempotent).

Adds, where missing:
  - a skip-to-content link as the first <body> child (WCAG 2.4.1 Bypass Blocks);
  - a <main id="main" tabindex="-1"> landmark wrapping the content after the
    #hubbar nav (WCAG 1.3.1) — this is also the skip-link target;
  - role="status" aria-live="polite" on quiz feedback (.fb) so the correct/wrong
    result is announced (WCAG 4.1.3);
  - removal of a dead legacy flashcard <script> on interview pages that threw a
    TypeError on load (getElementById('revealAll') is null).

The skip-link CSS + reduced-motion live in docs/assets/tokens.css; generated
glossary/resources get the same scaffolding from scripts/build-reference-pages.py;
the hub (docs/index.html) is handled in-page. Re-run after adding a new page:

    python3 scripts/inject-a11y.py
"""
import os, re, glob

ROOT = os.path.join(os.path.dirname(__file__), '..', 'docs')
SKIP = '<a class="skip-link" href="#main">Skip to content</a>'

# the wrap-closing </div> is the one followed only by an optional comment (e.g.
# </div><!-- /wrap -->) and <script>/<footer> blocks then </body> — anchor on that
# tail so content </div>s are never matched.
WRAP_CLOSE = re.compile(
    r'</div>((?:\s*<!--[\s\S]*?-->)?\s*'
    r'(?:<script[\s\S]*?</script>\s*|<footer[\s\S]*?</footer>\s*|<!--[\s\S]*?-->\s*)*</body>)', re.I)
LEGACY = re.compile(r'<script>\s*\n\s*function setFilter\b[\s\S]*?</script>\s*\n', re.I)


def is_target(path):
    rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
    if '/epub/' in '/' + rel:
        return False
    base = os.path.basename(rel).lower()
    if base in ('glossary.html', 'resources.html'):  # generated by build-reference-pages.py
        return False
    if rel == 'index.html':                            # hub handled in-page
        return False
    return True


def transform(s):
    notes = []
    # 1. skip-to-content link as first body child
    if 'class="skip-link"' not in s:
        s2 = re.sub(r'(<body[^>]*>)', r'\1\n' + SKIP, s, count=1)
        if s2 != s:
            s, _ = s2, notes.append('skip-link')
    # 2. <main> landmark: open after the first </nav> (hubbar), close before .wrap's </div>
    if '<main' not in s.lower():
        opened = re.sub(r'(</nav>)', r'\1\n<main id="main" tabindex="-1">', s, count=1)
        if opened != s and WRAP_CLOSE.search(opened):
            s, _ = WRAP_CLOSE.sub(r'</main>\n</div>\1', opened, count=1), notes.append('main')
    # 3. quiz feedback announced to AT
    s3 = re.sub(r'<(p|div) class="fb"(?![^>]*aria-live)', r'<\1 class="fb" role="status" aria-live="polite"', s)
    if s3 != s:
        s, _ = s3, notes.append('fb-live')
    # 4. drop the dead legacy flashcard script (interview pages)
    s4 = LEGACY.sub('', s, count=1)
    if s4 != s:
        s, _ = s4, notes.append('rm-dead-script')
    return s, notes


def main():
    changed = 0
    for path in glob.glob(os.path.join(ROOT, '**', '*.html'), recursive=True):
        if not is_target(path):
            continue
        s = open(path, encoding='utf-8').read()
        out, notes = transform(s)
        if out != s:
            open(path, 'w', encoding='utf-8').write(out)
            changed += 1
            print('  %-58s %s' % (os.path.relpath(path, ROOT), ', '.join(notes)))
    print('\n%d file(s) updated.' % changed)


if __name__ == '__main__':
    main()
